### ISSUE TITLE
VLC not detected

### ISSUE THREAD

**Issue by mamins1376** [geecko86/QuickLyric#101]
While i am listening to a music using VLC, QuickLyric gets song name from Walkman App(nowdays, it's name changed to 'Music') even Walkman is closed.

**Comment by geecko86** [comment]
Hey Mohammad,

Funny you should say that, since VLC is Open Source, I actually patched VLC myself to implement scrobbling and make it compatible with QuickLyric.

Could it be that the Walkman app is broadcasting the metadata for the last song it played on a regular basis? I know for a fact that their implementation of scrobbling is super messy.

**Comment by mamins1376** [comment]
yep, it is impossible right now.
I use XPERIA M2 Dual.
QuickLyric not detected VLC, even with disabled Walkman.
Walkman APK is available in both Google Play and XDA forum.

**Comment by geecko86** [comment]
Do you have the latest version of both QuickLyric and VLC?

**Comment by mamins1376** [comment]
yes.
VLC: 1.3.2
QuickLyric: 2.0Beta

**Comment by geecko86** [comment]
Odd. If disabling Sony Music doesn't work, then we can take it out of the equation. Is your music properly tagged?

Also, can you try installing some random scrobbler ([this](https://play.google.com/store/apps/details?id=com.adam.aslfms&hl=en) one maybe? It's also on GitHub and F-Droid). And see if it detects the music you play in VLC.

If it doesn't, it's a problem with either VLC or your device and you can close the issue. If it does, it's a problem with QL.
