### ISSUE TITLE
Used support libraries not found now

### ISSUE THREAD

**Issue by Animeshm77** [geecko86/QuickLyric#168]
Libraries used by quicklyric are not availbale now ....please update !

**Comment by geecko86** [comment]
I build QuickLyric every day and have no issues. I think the issue is on your side. What error output do you see?

**Comment by Animeshm77** [comment]
I am getting error in the support libraries that quicklyric used . Can u mail me all the support libraries at bfgxlucky@gmail.com .please mail.Thanx in advance :)

**Comment by Animeshm77** [comment]
For eg in com.squarehttp... In this library i am not able to import all files .

**Comment by geecko86** [comment]
Sounds like you're not familiar with Android development. Just use `gradle build ` and it will build. You don't need to worry about the libraries.

**Comment by Animeshm77** [comment]
Can i use quicklyric  in my project ?

**Comment by geecko86** [comment]
@Animeshm77 The code is open source, but you need to respect the [license](https://github.com/geecko86/QuickLyric/blob/master/LICENSE).

If you don't want to read it, here's a short summary: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

Pay attention in particular to the list of "Musts":
* You must give credit
* Your project *must* use this same license (GPLv3) and thus be open source
* You *must* send all your changes back to me.

Also be aware that you won't be allowed to use it commercially, since lyrics are subject to Copyright.
