### ISSUE TITLE
Add music recognition capability

### ISSUE THREAD

**Issue by ildar** [geecko86/QuickLyric#188]
It'd be awesome to have [Acoustic fingerprinting](https://en.wikipedia.org/wiki/Acoustic_fingerprint) integrated (aka Shazam). Maybe with Mic-in and/or currently played music.
As the service providers I'd think of [MusicBrainz](https://en.wikipedia.org/wiki/MusicBrainz#Fingerprinting) or [Gracenote](https://en.wikipedia.org/wiki/Gracenote#Products) which should have web API for that.

**Comment by geecko86** [comment]
Correct me if I'm wrong but Gracenote requires the use of their proprietary SDK for that.

My understanding is that MusicBrainz's API doesn't work for services like Shazam. It's meant to scan entire files so you can get the correct metadata for all your songs. If you can find an example of an app that uses the MusicBrainz API the way we need, I'd be happy to be proven wrong.

**Comment by ildar** [comment]
I see. Thanks for elaborating this. Looks it was just dreaming. :)

**Comment by Wabuo** [comment]
I think this would be a nice feature but I would hate if it would make MusicID services irrelevant because I like for example the history and add to spotify functions some MusicID Apps provide.

Also I like having the possibility to use different services if one cant find a song I can still try another one ...

**Comment by geecko86** [comment]
We've decided we're gonna use ACRCloud for this. Their SDK is perfectly compatible with our GPL requirements and they are the best on the market.

The only downside is that F-Droid users will need to input their own API key. A free user gets 100 requests per day.

**Comment by geecko86** [comment]
Suggestions regarding the UI are welcome.

A MusicID row will be added to the navigation drawer - a giant microphone button will likely be seen on the MusicID fragment.

How should the button behave, what should it look like, how should it animate, what happens when it's done recognizing, ... All these questions remain unanswered for now.

**Comment by geecko86** [comment]
Actually it looks like ACRCloud also requires the use of a proprietary binary file. Closing for now.
