### ISSUE TITLE
'Automatically refresh lyrics' sometimes becomes active when unchecked

### ISSUE THREAD

**Issue by svenoaks** [geecko86/QuickLyric#197]
Sometimes it behaves as if 'Automatically refresh lyrics' is checked even if it's not, happened one time after I enabled then disabled it later, until I enabled and disabled it again. Also just randomly a couple times. I'll see if I can consistently repo it.

**Comment by geecko86** [comment]
1. It always refreshes lyrics when you're reading synchronized lyrics. The idea behind that is that there is no use in having only the last two lines of a song on screen.
2. It also always refreshes when you enter onResume().

Having the setting enabled only matters if you're reading "static" lyrics, IIRC.

I believe these design choices make sense since they improve the overall experience for everyone without any down side - but I agree that it's a bit confusing.

**Comment by svenoaks** [comment]
Yeah i knew about the onResume(), didn't realize it was doing it when sync'd on purpose.

**Comment by geecko86** [comment]
Does that answer your question? If you don't think this makes sense, feel free to discuss it. Otherwise, I think we can close this.

**Comment by svenoaks** [comment]
Well, it confused me, I thought it was a bug, so you can use that info in weighting the design decision.
