### ISSUE TITLE
new lyrics source

### ISSUE THREAD

**Issue by astra1** [geecko86/QuickLyric#98]
darklyrics.com is very big lyrics catalog. It will be great if you write parser for this site

**Comment by geecko86** [comment]
Dark Lyrics focuses on lyrics for metal music. QuickLyric already fetches lyrics from metal-archives.

Can you make a case for Dark Lyrics? Why is it needed on top of Metal-Archives?

Note that you need to enable Metal in the settings if you wanna use Metal-Archives.

**Comment by astra1** [comment]
ok, version 1.8d from f-droid can't find A Swarm of  the Sun - Zenith (I enable Metal's checkbox)

new QuickLyric's 2.0 beta displays the lyrics, but there are crashes on my 5.1.1 nexus 4

**Comment by geecko86** [comment]
That's odd. There shouldn't be any difference regarding the *downloading* of lyrics.. But at least it's fixed.

Is this really the only song you had a problem with? If it is, then your problem is solved and you should close this issue.

Regarding the beta, I just got my hands back on my old Nexus 4 (with Android 4.2 on it) and I haven't had any crash.. I just uploaded a new APK, go ahead and try it. It's on Google+.
